# Generated by Django 4.2.9 on 2026-06-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_testcapture_source_video_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopographyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='topography/video/%Y/%m/%d/')),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('phone_model_id', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('calibration_state', models.CharField(choices=[('uncalibrated', 'Uncalibrated'), ('default', 'Default profile'), ('calibrated', 'Calibrated')], default='uncalibrated', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analysed', 'Analysed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topography_scans', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TopographyStill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topography/stills/%Y/%m/%d/')),
                ('index', models.IntegerField()),
                ('sharpness_score', models.FloatField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='topography.topographyscan')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TopographyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_overlay', models.ImageField(blank=True, upload_to='topography/overlays/%Y/%m/%d/')),
                ('axial_map', models.ImageField(blank=True, upload_to='topography/axial/%Y/%m/%d/')),
                ('sim_k_flat', models.FloatField(blank=True, null=True)),
                ('sim_k_steep', models.FloatField(blank=True, null=True)),
                ('sim_k_axis', models.FloatField(blank=True, null=True)),
                ('central_k', models.FloatField(blank=True, null=True)),
                ('astigmatism_magnitude', models.FloatField(blank=True, null=True)),
                ('astigmatism_axis', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('algorithm_version', models.CharField(blank=True, max_length=20)),
                ('calibration_state', models.CharField(blank=True, max_length=20)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='topography.topographyscan')),
            ],
        ),
    ]
