# Generated by Django 5.1.15 on 2026-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topographyscan',
            name='camera_focal_px',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
