# Generated by Django 5.1.15 on 2026-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0002_topographyscan_camera_focal_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='topographyscan',
            name='capture_height_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topographyscan',
            name='capture_width_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
