export interface CountryCode {
  country: string
  dialCode: string  // e.g. '44'
  isoCode: string   // ISO 3166-1 alpha-2, e.g. 'GB'
}

const ALPHABETICAL: CountryCode[] = [
  { country: 'Afghanistan', dialCode: '93', isoCode: 'AF' },
  { country: 'Albania', dialCode: '355', isoCode: 'AL' },
  { country: 'Algeria', dialCode: '213', isoCode: 'DZ' },
  { country: 'Argentina', dialCode: '54', isoCode: 'AR' },
  { country: 'Armenia', dialCode: '374', isoCode: 'AM' },
  { country: 'Australia', dialCode: '61', isoCode: 'AU' },
  { country: 'Austria', dialCode: '43', isoCode: 'AT' },
  { country: 'Azerbaijan', dialCode: '994', isoCode: 'AZ' },
  { country: 'Bahrain', dialCode: '973', isoCode: 'BH' },
  { country: 'Bangladesh', dialCode: '880', isoCode: 'BD' },
  { country: 'Belarus', dialCode: '375', isoCode: 'BY' },
  { country: 'Belgium', dialCode: '32', isoCode: 'BE' },
  { country: 'Bolivia', dialCode: '591', isoCode: 'BO' },
  { country: 'Bosnia and Herzegovina', dialCode: '387', isoCode: 'BA' },
  { country: 'Brazil', dialCode: '55', isoCode: 'BR' },
  { country: 'Bulgaria', dialCode: '359', isoCode: 'BG' },
  { country: 'Cambodia', dialCode: '855', isoCode: 'KH' },
  { country: 'Canada', dialCode: '1', isoCode: 'CA' },
  { country: 'Chile', dialCode: '56', isoCode: 'CL' },
  { country: 'China', dialCode: '86', isoCode: 'CN' },
  { country: 'Colombia', dialCode: '57', isoCode: 'CO' },
  { country: 'Croatia', dialCode: '385', isoCode: 'HR' },
  { country: 'Cyprus', dialCode: '357', isoCode: 'CY' },
  { country: 'Czech Republic', dialCode: '420', isoCode: 'CZ' },
  { country: 'Denmark', dialCode: '45', isoCode: 'DK' },
  { country: 'Ecuador', dialCode: '593', isoCode: 'EC' },
  { country: 'Egypt', dialCode: '20', isoCode: 'EG' },
  { country: 'Estonia', dialCode: '372', isoCode: 'EE' },
  { country: 'Ethiopia', dialCode: '251', isoCode: 'ET' },
  { country: 'Finland', dialCode: '358', isoCode: 'FI' },
  { country: 'France', dialCode: '33', isoCode: 'FR' },
  { country: 'Georgia', dialCode: '995', isoCode: 'GE' },
  { country: 'Germany', dialCode: '49', isoCode: 'DE' },
  { country: 'Ghana', dialCode: '233', isoCode: 'GH' },
  { country: 'Greece', dialCode: '30', isoCode: 'GR' },
  { country: 'Hong Kong', dialCode: '852', isoCode: 'HK' },
  { country: 'Hungary', dialCode: '36', isoCode: 'HU' },
  { country: 'Iceland', dialCode: '354', isoCode: 'IS' },
  { country: 'India', dialCode: '91', isoCode: 'IN' },
  { country: 'Indonesia', dialCode: '62', isoCode: 'ID' },
  { country: 'Iran', dialCode: '98', isoCode: 'IR' },
  { country: 'Iraq', dialCode: '964', isoCode: 'IQ' },
  { country: 'Ireland', dialCode: '353', isoCode: 'IE' },
  { country: 'Israel', dialCode: '972', isoCode: 'IL' },
  { country: 'Italy', dialCode: '39', isoCode: 'IT' },
  { country: 'Japan', dialCode: '81', isoCode: 'JP' },
  { country: 'Jordan', dialCode: '962', isoCode: 'JO' },
  { country: 'Kazakhstan', dialCode: '7', isoCode: 'KZ' },
  { country: 'Kenya', dialCode: '254', isoCode: 'KE' },
  { country: 'Kuwait', dialCode: '965', isoCode: 'KW' },
  { country: 'Latvia', dialCode: '371', isoCode: 'LV' },
  { country: 'Lebanon', dialCode: '961', isoCode: 'LB' },
  { country: 'Libya', dialCode: '218', isoCode: 'LY' },
  { country: 'Lithuania', dialCode: '370', isoCode: 'LT' },
  { country: 'Luxembourg', dialCode: '352', isoCode: 'LU' },
  { country: 'Malaysia', dialCode: '60', isoCode: 'MY' },
  { country: 'Malta', dialCode: '356', isoCode: 'MT' },
  { country: 'Mexico', dialCode: '52', isoCode: 'MX' },
  { country: 'Morocco', dialCode: '212', isoCode: 'MA' },
  { country: 'Netherlands', dialCode: '31', isoCode: 'NL' },
  { country: 'New Zealand', dialCode: '64', isoCode: 'NZ' },
  { country: 'Nigeria', dialCode: '234', isoCode: 'NG' },
  { country: 'Norway', dialCode: '47', isoCode: 'NO' },
  { country: 'Oman', dialCode: '968', isoCode: 'OM' },
  { country: 'Pakistan', dialCode: '92', isoCode: 'PK' },
  { country: 'Peru', dialCode: '51', isoCode: 'PE' },
  { country: 'Philippines', dialCode: '63', isoCode: 'PH' },
  { country: 'Poland', dialCode: '48', isoCode: 'PL' },
  { country: 'Portugal', dialCode: '351', isoCode: 'PT' },
  { country: 'Qatar', dialCode: '974', isoCode: 'QA' },
  { country: 'Romania', dialCode: '40', isoCode: 'RO' },
  { country: 'Russia', dialCode: '7', isoCode: 'RU' },
  { country: 'Saudi Arabia', dialCode: '966', isoCode: 'SA' },
  { country: 'Serbia', dialCode: '381', isoCode: 'RS' },
  { country: 'Singapore', dialCode: '65', isoCode: 'SG' },
  { country: 'Slovakia', dialCode: '421', isoCode: 'SK' },
  { country: 'Slovenia', dialCode: '386', isoCode: 'SI' },
  { country: 'South Africa', dialCode: '27', isoCode: 'ZA' },
  { country: 'South Korea', dialCode: '82', isoCode: 'KR' },
  { country: 'Spain', dialCode: '34', isoCode: 'ES' },
  { country: 'Sri Lanka', dialCode: '94', isoCode: 'LK' },
  { country: 'Sweden', dialCode: '46', isoCode: 'SE' },
  { country: 'Switzerland', dialCode: '41', isoCode: 'CH' },
  { country: 'Syria', dialCode: '963', isoCode: 'SY' },
  { country: 'Taiwan', dialCode: '886', isoCode: 'TW' },
  { country: 'Tanzania', dialCode: '255', isoCode: 'TZ' },
  { country: 'Thailand', dialCode: '66', isoCode: 'TH' },
  { country: 'Tunisia', dialCode: '216', isoCode: 'TN' },
  { country: 'Turkey', dialCode: '90', isoCode: 'TR' },
  { country: 'Uganda', dialCode: '256', isoCode: 'UG' },
  { country: 'Ukraine', dialCode: '380', isoCode: 'UA' },
  { country: 'United Arab Emirates', dialCode: '971', isoCode: 'AE' },
  { country: 'United States', dialCode: '1', isoCode: 'US' },
  { country: 'Uzbekistan', dialCode: '998', isoCode: 'UZ' },
  { country: 'Venezuela', dialCode: '58', isoCode: 'VE' },
  { country: 'Vietnam', dialCode: '84', isoCode: 'VN' },
  { country: 'Yemen', dialCode: '967', isoCode: 'YE' },
  { country: 'Zimbabwe', dialCode: '263', isoCode: 'ZW' },
]

export const COUNTRY_CODES: CountryCode[] = [
  { country: 'United Kingdom', dialCode: '44', isoCode: 'GB' },
  ...ALPHABETICAL,
]
