# Generated by Django 5.1.15 on 2026-06-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_onboardingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model_id', models.CharField(max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('attachment_id', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(choices=[('default_profile', 'Default profile'), ('reference_object', 'Reference-object')], default='reference_object', max_length=20)),
                ('camera_intrinsics', models.JSONField(blank=True, default=dict)),
                ('attachment_geometry', models.JSONField(blank=True, default=dict)),
                ('solve_result', models.JSONField(blank=True, default=dict)),
                ('calibration_version', models.CharField(default='calib-v0.1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_calibrations', to='accounts.practice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
