# Generated by Django 5.1.15 on 2026-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nhs_number',
            field=models.CharField(max_length=20),
        ),
    ]
