# Generated by Django 5.1.15 on 2026-06-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Practice Admin'), ('clinician', 'Clinician'), ('technician', 'Technician')], default='clinician', max_length=20)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to='accounts.clinician')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to='accounts.clinician')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.practice')),
            ],
        ),
    ]
