# Generated by Django 5.1.15 on 2026-06-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('capturing', 'Capturing'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='capturing', max_length=20)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='accounts.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('nibut', 'NIBUT'), ('fluorescein', 'Fluorescein Break-Up'), ('lipid', 'Lipid Layer')], max_length=20)),
                ('video_file', models.FileField(upload_to='captures/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('resolution_width', models.IntegerField(blank=True, null=True)),
                ('resolution_height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analysed', 'Analysed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nibut_first_breakup_seconds', models.FloatField(blank=True, null=True)),
                ('nibut_mean_breakup_seconds', models.FloatField(blank=True, null=True)),
                ('nibut_heatmap', models.ImageField(blank=True, upload_to='heatmaps/%Y/%m/%d/')),
                ('fluorescein_grade', models.IntegerField(blank=True, null=True)),
                ('fluorescein_breakup_seconds', models.FloatField(blank=True, null=True)),
                ('lipid_grade', models.IntegerField(blank=True, null=True)),
                ('lipid_thickness_nm', models.FloatField(blank=True, null=True)),
                ('tear_meniscus_height_mm', models.FloatField(blank=True, null=True)),
                ('dry_eye_severity', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analysis_version', models.CharField(blank=True, max_length=20)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.testcapture')),
            ],
        ),
    ]
