# Generated by Django 5.1.15 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcapture',
            name='source',
            field=models.CharField(
                choices=[('mobile', 'Mobile'), ('manual', 'Manual')],
                default='mobile',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='testcapture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='captures/%Y/%m/%d/'),
        ),
    ]
