# Generated by Django 5.1.15 on 2026-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_testcapture_source_video_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcapture',
            name='source',
            field=models.CharField(choices=[('mobile', 'Mobile camera'), ('upload', 'Uploaded file'), ('manual', 'Manual entry (no video)')], default='mobile', max_length=10),
        ),
    ]
