# Generated by Django 5.1.15 on 2026-06-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_testcapture_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureStill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stills/%Y/%m/%d/')),
                ('timestamp_seconds', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='assessments.testcapture')),
            ],
            options={
                'ordering': ['timestamp_seconds'],
            },
        ),
    ]
